version: '3'

services:
  ai_assisted_diary_app:
    build: .
    volumes:
      - .:/app
      - logs_volume:/app/logs
    depends_on:
      db:
        condition: service_healthy  # Wait for the 'db' service to be healthy
    environment:
      DOCKER_CONTAINER: 1
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ai_assisted_diary
      MYSQL_USER: admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_DIARY_URL: ${AI_DIARY_URL}
      AI_DIARY_BEARER: ${AI_DIARY_BEARER}
      AI_USER_NAME: ${AI_USER_NAME}
      AI_USER_EMAIL: ${AI_USER_EMAIL}
      AI_USER_HASH: ${AI_USER_HASH}

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ai_assisted_diary
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    healthcheck:
        test: "mariadb ${MYSQL_DATABASE} -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
        interval: 2s
        timeout: 2s
        retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  logs_volume:  # Define the logs volume
  driver: local  # Optional: Specify the volume driver (defaults to 'local')
  driver_opts:  # Optional: Specify driver options
    type: 'none'  # Optional: Specify the type of volume (defaults to 'none')
    device: '/var/log/myapp'  
